# Generated by Django 3.2.20 on 2023-08-09 09:00

from django.db import migrations, models


# @cf::ornament.checkupcenter
class Migration(migrations.Migration):
    dependencies = [
        ("checkupcenter", "0001_initial"),
        ("product", "0186_remove_product_charge_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="checkup_product_categories",
            field=models.ManyToManyField(
                blank=True, to="checkupcenter.CheckUpProductCategory"
            ),
        ),
    ]
