# Generated by Django 3.2.23 on 2024-01-19 10:48

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0190_merge_20231221_1356"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("product_collectionchannellisting", "published_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("product_collectionchannellisting", "published_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("product_digitalcontenturl", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("product_digitalcontenturl", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("product_product", "updated_at")}
            {form_alter_timestamp_column_sql("product_product", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("product_product", "updated_at", True)}
            {form_alter_timestamp_column_sql("product_product", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("product_productchannellisting", "published_at")}
            {form_alter_timestamp_column_sql("product_productchannellisting", "available_for_purchase_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("product_productchannellisting", "published_at", True)}
            {form_alter_timestamp_column_sql("product_productchannellisting", "available_for_purchase_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("product_productvariant", "preorder_end_date")}
            {form_alter_timestamp_column_sql("product_productvariant", "created_at")}
            {form_alter_timestamp_column_sql("product_productvariant", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("product_productvariant", "preorder_end_date", True)}
            {form_alter_timestamp_column_sql("product_productvariant", "created_at", True)}
            {form_alter_timestamp_column_sql("product_productvariant", "updated_at", True)}
            """
            ],
        ),
    ]
