# Generated by Django 3.2.23 on 2024-01-18 14:43

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("channel", "0018_auto_20240118_1412"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("channel_channel", "created_at")}
            {form_alter_timestamp_column_sql("channel_channel", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("channel_channel", "created_at", True)}
            {form_alter_timestamp_column_sql("channel_channel", "updated_at", True)}
            """
            ],
        ),
    ]
