# Generated by Django 3.2.20 on 2023-08-09 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0186_remove_product_charge_taxes'),
        ('account', '0082_user_last_confirm_email_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_calculatable', models.BooleanField(default=True)),
                ('is_base', models.BooleanField(default=False)),
                ('is_personalized', models.BooleanField(default=False)),
                ('profile_uuid', models.UUIDField()),
                ('matched_at', models.DateTimeField(editable=False, null=True)),
                ('personalized_at', models.DateTimeField(editable=False, null=True)),
                ('calculated_at', models.DateTimeField(editable=False, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'checkup',
                'verbose_name_plural': 'checkups',
                'db_table': 'checkupcenter_checkup',
            },
        ),
        migrations.CreateModel(
            name='CheckUpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, max_length=8, null=True)),
                ('ext_id', models.CharField(max_length=32, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'checkup category',
                'verbose_name_plural': 'checkup categories',
                'db_table': 'checkupcenter_checkup_category',
            },
        ),
        migrations.CreateModel(
            name='CheckUpProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ext_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('human_part_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'checkup product category',
                'verbose_name_plural': 'checkup product categories',
                'db_table': 'checkupcenter_checkup_product_category',
            },
        ),
        migrations.CreateModel(
            name='CheckUpTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('is_active', models.BooleanField(default=True)),
                ('is_calculatable', models.BooleanField(default=True)),
                ('is_base', models.BooleanField(default=False)),
                ('is_personalized', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkupcenter.checkupcategory')),
            ],
            options={
                'verbose_name': 'checkup template',
                'verbose_name_plural': 'checkup templates',
                'db_table': 'checkupcenter_checkup_template',
            },
        ),
        migrations.CreateModel(
            name='CheckUpTemplateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkupcenter.checkuptemplate')),
            ],
            options={
                'verbose_name': 'checkup template product',
                'verbose_name_plural': 'checkup template products',
                'db_table': 'checkupcenter_checkup_template_product',
            },
        ),
        migrations.AddField(
            model_name='checkuptemplate',
            name='products',
            field=models.ManyToManyField(through='checkupcenter.CheckUpTemplateProduct', to='product.Product'),
        ),
        migrations.CreateModel(
            name='CheckUpState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('partial', 'Partial'), ('full', 'Full'), ('most-filled', 'Most filled')], max_length=16, null=True)),
                ('approvement', models.CharField(blank=True, choices=[('need-to-ask', 'Need to ask'), ('approved', 'Approved'), ('not-approved', 'Not approved')], max_length=16, null=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_states', to='checkupcenter.checkup')),
            ],
            options={
                'verbose_name': 'checkup state',
                'verbose_name_plural': 'checkup states',
                'db_table': 'checkupcenter_checkup_state',
            },
        ),
        migrations.CreateModel(
            name='CheckUpProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_personalized', models.BooleanField(default=False)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('checkup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkup_products', to='checkupcenter.checkup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'checkup product',
                'verbose_name_plural': 'checkup products',
                'db_table': 'checkupcenter_checkup_product',
            },
        ),
        migrations.AddField(
            model_name='checkup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkupcenter.checkupcategory'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkups_personalized', to='checkupcenter.checkup'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='products',
            field=models.ManyToManyField(through='checkupcenter.CheckUpProduct', to='product.Product'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkupcenter.checkuptemplate'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.CreateModel(
            name='CheckUpTemplateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='checkupcenter.checkuptemplate')),
            ],
            options={
                'verbose_name': 'checkup template translation',
                'verbose_name_plural': 'checkup template translations',
                'db_table': 'checkupcenter_checkup_template_translation',
                'unique_together': {('template', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='CheckUpProductCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='checkupcenter.checkupproductcategory')),
            ],
            options={
                'verbose_name': 'checkup product category translation',
                'verbose_name_plural': 'checkup product category translations',
                'db_table': 'checkupcenter_checkup_product_category_translation',
                'unique_together': {('category', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='CheckUpCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='checkupcenter.checkupcategory')),
            ],
            options={
                'verbose_name': 'checkup category translation',
                'verbose_name_plural': 'checkup category translations',
                'db_table': 'checkupcenter_checkup_category_translation',
                'unique_together': {('category', 'language_code')},
            },
        ),
    ]
