# Generated by Django 3.2.23 on 2024-01-18 15:06

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("checkupcenter", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "matched_at")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "personalized_at")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "calculated_at")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "matched_at", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "personalized_at", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "calculated_at", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_category", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_category", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_category", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_category", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product_category", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product_category", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product_category", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_product_category", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "date_from")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "date_to")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "date_from", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "date_to", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_state", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template_product", "created")}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template_product", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template_product", "created", True)}
            {form_alter_timestamp_column_sql("checkupcenter_checkup_template_product", "updated", True)}
            """
            ],
        ),
    ]
