# Generated by Django 3.2.23 on 2024-01-18 14:38

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0027_set_identifier_when_missing"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("app_app", "created_at")}
            {form_alter_timestamp_column_sql("app_app", "removed_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("app_app", "created_at", True)}
            {form_alter_timestamp_column_sql("app_app", "removed_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("app_appinstallation", "created_at")}
            {form_alter_timestamp_column_sql("app_appinstallation", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("app_appinstallation", "created_at", True)}
            {form_alter_timestamp_column_sql("app_appinstallation", "updated_at", True)}
            """
            ],
        ),
    ]
