# Generated by Django 3.2.25 on 2024-08-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_no_tz'),
        ('app', '0029_alter_app_identifier'),
    ]

    operations = [
    ]
