# Generated by Django 3.2.23 on 2024-01-19 10:53

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0033_warehouse_external_reference"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("warehouse_preorderreservation", "reserved_until")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("warehouse_preorderreservation", "reserved_until", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("warehouse_reservation", "reserved_until")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("warehouse_reservation", "reserved_until", True)}
            """
            ],
        ),
    ]
