# Generated by Django 3.2.20 on 2023-08-28 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0014_channel_allow_to_create_order_without_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('latitude', models.DecimalField(decimal_places=15, help_text='<a href="http://www.mapcoordinates.net/ru" target="_blank">http://www.mapcoordinates.net/ru</a>', max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, help_text='<a href="http://www.mapcoordinates.net/ru" target="_blank">http://www.mapcoordinates.net/ru</a>', max_digits=18)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
            options={
                'db_table': 'ornament_geo_city',
            },
        ),
    ]
