# Generated by Django 3.2.23 on 2024-01-19 08:43

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_geo_city", "created")}
            {form_alter_timestamp_column_sql("ornament_geo_city", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_geo_city", "created", True)}
            {form_alter_timestamp_column_sql("ornament_geo_city", "updated", True)}
            """
            ],
        ),
    ]
