# Generated by Django 3.2.23 on 2024-01-19 08:45

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_alter_vendorrule_user"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor", "created")}
            {form_alter_timestamp_column_sql("ornament_vendor", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor", "created", True)}
            {form_alter_timestamp_column_sql("ornament_vendor", "updated", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor_rule", "created")}
            {form_alter_timestamp_column_sql("ornament_vendor_rule", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor_rule", "created", True)}
            {form_alter_timestamp_column_sql("ornament_vendor_rule", "updated", True)}
            """
            ],
        ),
    ]
