# Generated by Django 3.2.23 on 2024-01-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_no_tz"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="transaction_flow",
            field=models.BooleanField(default=False),
        ),
    ]
