# Generated by Django 3.2.23 on 2024-03-06 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_vendor_transaction_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorDealType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_flow", models.BooleanField(default=False)),
                ("home_visit", models.BooleanField(default=False)),
                ("shipment", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ornament_vendor_deal_type",
            },
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="transaction_flow",
        ),
        migrations.AddField(
            model_name="vendor",
            name="deal_type",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendors.vendordealtype",
            ),
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor_deal_type", "created")}
            {form_alter_timestamp_column_sql("ornament_vendor_deal_type", "updated")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("ornament_vendor_deal_type", "created", True)}
            {form_alter_timestamp_column_sql("ornament_vendor_deal_type", "updated", True)}
            """
            ],
        ),
    ]
