# Generated by Django 3.2.23 on 2024-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20240306_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordealtype',
            name='map_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendordealtype',
            name='visit_time',
            field=models.BooleanField(default=False),
        ),
    ]
