# Generated by Django 3.2.23 on 2024-01-18 14:46

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        (
            "checkout",
            "0062_update_checkout_last_transaction_modified_at_and_refundable",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkout_checkout", "created_at")}
            {form_alter_timestamp_column_sql("checkout_checkout", "last_change")}
            {form_alter_timestamp_column_sql("checkout_checkout", "price_expiration")}
            {form_alter_timestamp_column_sql("checkout_checkout", "last_transaction_modified_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkout_checkout", "created_at", True)}
            {form_alter_timestamp_column_sql("checkout_checkout", "last_change", True)}
            {form_alter_timestamp_column_sql("checkout_checkout", "price_expiration", True)}
            {form_alter_timestamp_column_sql("checkout_checkout", "last_transaction_modified_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("checkout_checkoutline", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("checkout_checkoutline", "created_at", True)}
            """
            ],
        ),
    ]
