# Generated by Django 3.2.25 on 2024-08-13 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0069_merge_20240514_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='price_expiration',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
