# Generated by Django 3.2.21 on 2023-09-20 11:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('channel', '0016_auto_20230816_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDLDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('retail', 'Retail'), ('corporate', 'Corporate')], default='retail', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('doctor_id', models.CharField(blank=True, max_length=255)),
                ('clinic_id', models.CharField(max_length=255)),
                ('laboratory_id', models.CharField(max_length=255)),
                ('laboratory_name', models.CharField(max_length=255)),
                ('discount_title', models.CharField(max_length=255)),
                ('discount_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.channel')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city')),
            ],
            options={
                'ordering': ('-discount_value', '-channel', '-id'),
            },
        ),
    ]
