# Generated by Django 3.2.23 on 2024-01-18 14:41

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("attribute", "0039_merge_20231113_1132"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("attribute_attributevalue", "date_time")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("attribute_attributevalue", "date_time", True)}
            """
            ],
        ),
    ]
