# Generated by Django 3.2.25 on 2024-09-09 13:34

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0047_auto_20240909_1333"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("attribute_attributevalue", "created_at")}
            {form_alter_timestamp_column_sql("attribute_attributevalue", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("attribute_attributevalue", "created_at", True)}
            {form_alter_timestamp_column_sql("attribute_attributevalue", "updated_at", True)}
            """
            ],
        ),
    ]
