# Generated by Django 3.2.23 on 2024-01-19 08:17

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_drop_vatlayer_tables"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventdelivery", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventdelivery", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventdeliveryattempt", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventdeliveryattempt", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventpayload", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("core_eventpayload", "created_at", True)}
            """
            ],
        ),
    ]
