# Generated by Django 3.2.23 on 2024-01-19 08:20

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0073_auto_20231213_1535"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_checkoutlinediscount", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_checkoutlinediscount", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_orderdiscount", "created_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_orderdiscount", "created_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_voucher", "start_date")}
            {form_alter_timestamp_column_sql("discount_voucher", "end_date")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("discount_voucher", "start_date", True)}
            {form_alter_timestamp_column_sql("discount_voucher", "end_date", True)}
            """
            ],
        ),
    ]
