# Generated by Django 3.2.25 on 2024-08-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0073_add_unique_type'),
        ('discount', '0083_auto_20240510_0838'),
    ]

    operations = [
    ]
