# Generated by Django 3.2.21 on 2023-09-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
        ("order", "0174_order_idx_order_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo.city",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="external_lab_id",
            field=models.CharField(
                blank=True, default=None, max_length=36, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="external_lab_order_id",
            field=models.CharField(
                blank=True, default=None, max_length=36, null=True, unique=True
            ),
        ),
    ]
