# Generated by Django 3.2.22 on 2023-10-30 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("order", "0176_alter_orderevent_type")]

    operations = []
