# Generated by Django 3.2.23 on 2023-11-22 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0176_alter_orderevent_type"),
    ]

    operations = []
