# Generated by Django 3.2.23 on 2023-11-03 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0174_merge_20231030_1033'),
        ('order', '0177_set_order_voucher_code'),
    ]

    operations = [
    ]
