# Generated by Django 3.2.23 on 2024-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0171_order_order_user_email_user_id_idx'),
        ('order', '0174_merge_20231030_1033'),
        ('order', '0181_order_subtotal_as_a_field'),
    ]

    operations = [
    ]
