# Generated by Django 3.2.23 on 2024-01-19 08:33

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0183_auto_20240118_1411"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("order_fulfillment", "created_at")}
            {form_alter_timestamp_column_sql("order_fulfillment", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("order_fulfillment", "created_at", True)}
            {form_alter_timestamp_column_sql("order_fulfillment", "updated_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("order_order", "created_at")}
            {form_alter_timestamp_column_sql("order_order", "updated_at")}
            {form_alter_timestamp_column_sql("order_order", "expired_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("order_order", "created_at", True)}
            {form_alter_timestamp_column_sql("order_order", "updated_at", True)}
            {form_alter_timestamp_column_sql("order_order", "expired_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("order_orderevent", "date")}
            {form_alter_timestamp_column_sql("order_orderevent", "created_at")}
            {form_alter_timestamp_column_sql("order_orderevent", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("order_orderevent", "date", True)}
            {form_alter_timestamp_column_sql("order_orderevent", "created_at", True)}
            {form_alter_timestamp_column_sql("order_orderevent", "updated_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("order_ordergrantedrefund", "created_at")}
            {form_alter_timestamp_column_sql("order_ordergrantedrefund", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("order_ordergrantedrefund", "created_at", True)}
            {form_alter_timestamp_column_sql("order_ordergrantedrefund", "updated_at", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("order_orderline", "created_at")}
            {form_alter_timestamp_column_sql("order_orderline", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("order_orderline", "created_at", True)}
            {form_alter_timestamp_column_sql("order_orderline", "updated_at", True)}
            """
            ],
        ),
    ]
