# Generated by Django 3.2.22 on 2024-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0184_no_tz"),
    ]

    operations = []
