# Generated by Django 3.2.20 on 2023-08-11 12:20

from django.db import migrations, models


# @cf::ornament.saleor.account
class Migration(migrations.Migration):
    dependencies = [
        ("account", "0082_user_last_confirm_email_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sso_id",
            field=models.UUIDField(
                default=None, editable=False, null=True, unique=True
            ),
        ),
    ]
