# Generated by Django 3.2.20 on 2023-08-17 12:13

from django.db import migrations, models
import django.utils.timezone


# @cf::ornament.saleor.account
class Migration(migrations.Migration):
    dependencies = [
        ("account", "0083_user_sso_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unspecified")],
                default="U",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
