# Generated by Django 3.2.24 on 2024-02-29 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0084_auto_20230817_1213"),
    ]

    operations = []
