# Generated by Django 3.2.20 on 2023-08-30 09:11

from django.db import migrations, models
import django.db.models.deletion


# @cf::ornament.saleor.account
class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_alter_vendorrule_user"),
        ("geo", "0001_initial"),
        ("account", "0084_auto_20230817_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo.city",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendors.vendor",
            ),
        ),
    ]
