# Generated by Django 3.2.23 on 2024-01-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_merge_20231205_1315'),
        ('account', '0085_auto_20230830_0911'),
    ]

    operations = [
    ]
