# Generated by Django 3.2.23 on 2024-01-18 09:07

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0086_merge_20240110_1408"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("account_address", "updated")}
            {form_alter_timestamp_column_sql("account_address", "created")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("account_address", "updated", True)}
            {form_alter_timestamp_column_sql("account_address", "created", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("account_customerevent", "date")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("account_customerevent", "date", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("account_customernote", "date")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("account_customernote", "date", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("account_user", "date_joined")}
            {form_alter_timestamp_column_sql("account_user", "last_login")}
            {form_alter_timestamp_column_sql("account_user", "updated_at")}
            {form_alter_timestamp_column_sql("account_user", "last_password_reset_request")}
            {form_alter_timestamp_column_sql("account_user", "last_confirm_email_request")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("account_user", "date_joined", True)}
            {form_alter_timestamp_column_sql("account_user", "last_login", True)}
            {form_alter_timestamp_column_sql("account_user", "updated_at", True)}
            {form_alter_timestamp_column_sql("account_user", "last_password_reset_request", True)}
            {form_alter_timestamp_column_sql("account_user", "last_confirm_email_request", True)}
            """
            ],
        ),
    ]
