# Generated by Django 3.2.25 on 2024-08-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_confirm_active_user'),
        ('account', '0085_address_validation_skipped'),
        ('account', '0087_no_tz'),
    ]

    operations = [
    ]
