# Generated by Django 3.2.25 on 2024-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_merge_20240802_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sso_id',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
