# Generated by Django 3.2.23 on 2024-01-19 08:27

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("giftcard", "0020_search_vector_index"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("giftcard_giftcard", "created_at")}
            {form_alter_timestamp_column_sql("giftcard_giftcard", "last_used_on")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("giftcard_giftcard", "created_at", True)}
            {form_alter_timestamp_column_sql("giftcard_giftcard", "last_used_on", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("giftcard_giftcardevent", "date")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("giftcard_giftcardevent", "date", True)}
            """
            ],
        ),
    ]
