# Generated by Django 3.2.23 on 2024-01-19 08:18

from django.db import migrations

from saleor.utils.migrations import form_alter_timestamp_column_sql


class Migration(migrations.Migration):
    dependencies = [
        ("csv", "0004_auto_20210709_1043"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("csv_exportevent", "date")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("csv_exportevent", "date", True)}
            """
            ],
        ),
        migrations.RunSQL(
            sql=[
                f"""
            {form_alter_timestamp_column_sql("csv_exportfile", "created_at")}
            {form_alter_timestamp_column_sql("csv_exportfile", "updated_at")}
            """
            ],
            reverse_sql=[
                f"""
            {form_alter_timestamp_column_sql("csv_exportfile", "created_at", True)}
            {form_alter_timestamp_column_sql("csv_exportfile", "updated_at", True)}
            """
            ],
        ),
    ]
